# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ch67v003d-capi-aws
  namespace: ch67v003d
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ch67v003d-capi-aws
subjects:
- kind: ServiceAccount
  name: ch67v003d-capi-aws
